name: CI

on: 
    schedule:
        - cron: "45 15 * * 1-5"
         
    workflow_dispatch:   
        inputs:
            os:
                description: 'Выберите операционную систему'
                required: true
                default: 'ubuntu'
                type: choice    
                options:
                    - windows   
                    - ubuntu    
            environment:
                description: 'Выберите окружение для тестирования'
                required: true
                default: 'Test'
                type: choice
                options:
                    - Test
                    - Prod
                            
jobs:
  build:
    runs-on: ${{ inputs.os == 'windows' && 'windows-latest' || 'ubuntu-latest' }}

    steps:
    
      - name: Получи код из уд. репозитория
        uses: actions/checkout@v4  

      - name: Установка Node.js
        uses: actions/setup-node@v4 
        with:
          node-version: '18'  

      - name: Установка Newman, HTML Extra Reporter, JSON Reporter
        run: | 
            npm install -g newman 
            npm install -g newman-reporter-htmlextra 
            npm install -g newman-reporter-json 
        
      - name: Запуск тестов с формированием отчетов
        env:
            API_KEY: ${{ secrets.API_KEY }}
            API_TOKEN: ${{ secrets.API_TOKEN }}
            BASE_URL: ${{ secrets.BASE_URL }}
        run: |
          newman run Maxim_Trello.postman_collection.json \
            -e Test_Trello_Environment.postman_environment.json \
            --env-var "key=${API_KEY}" \
            --env-var "token=${API_TOKEN}" \
            --env-var "base_url=${BASE_URL}" \
            -r htmlextra,json \
            --reporter-htmlextra-export test-results/html-report.html \
            --reporter-json-export test-results/json-report.json
        
      - name: Загрузка HTML отчета как артефакт
        uses: actions/upload-artifact@v4
        with:
          name: html-test-report
          path: test-results/html-report.html
          
      - name: Загрузка JSON отчета как артефакт
        uses: actions/upload-artifact@v4
        with:
          name: json-test-report
          path: test-results/json-report.json
          
      - name: Отправка HTML-отчёта на Яндекс.Почту
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.yandex.ru
          server_port: 465
          secure: true
          username: ${{ secrets.YANDEX_EMAIL }}
          password: ${{ secrets.YANDEX_APP_PASSWORD }}
          subject: "[GitHub Actions] Отчёт о тестировании Trello API"
          to: ${{ secrets.RECIPIENT_EMAIL }}
          from: GitHub Actions <${{ secrets.YANDEX_EMAIL }}>
